#define F_CPU 8000000
#include <avr/io.h>
#include <util/delay.h>
#include <avr/interrupt.h>
#include "Afficheur7segments.h"
#include "PWM.h"
#define VITESSE_INITIALE_MAN1 90
#define VITESSE_INITIALE_MAN2 90
#define VITESSE_INITIALE_MAN3 50
#define VITESSE_INITIALE_MAN4 50
#define VITESSE_INITIALE_MAN5 50
#define VITESSE_INITIALE_MAN6 90
#define VITESSE_FINALE_MAN1 90
#define VITESSE_FINALE_MAN2 90
#define VITESSE_FINALE_MAN3 78
#define VITESSE_FINALE_MAN4 78
#define VITESSE_FINALE_MAN5 63
#define VITESSE_FINALE_MAN6 41
#define VITESSE_IINTERMEDIAIRE_MAN1 52
#define VITESSE_IINTERMEDIAIRE_MAN2 52
#define VITESSE_IINTERMEDIAIRE_MAN3 66
#define VITESSE_IINTERMEDIAIRE_MAN4 66
#define VITESSE_IINTERMEDIAIRE_MAN5 0
#define SPEED_CHANGE_RATE_MAN1 1
#define SPEED_CHANGE_RATE_MAN2 1
#define SPEED_CHANGE_RATE_MAN5 3
#define SPEED_CHANGE_RATE_MAN6 7
#define DELAI_CHANGEMENT_VITESSE_MAN1 4
#define DELAI_CHANGEMENT_VITESSE_MAN2 4
#define DELAI_CHANGEMENT_VITESSE_MAN5 5
#define DELAI_CHANGEMENT_VITESSE_MAN6 20
#define DELAI_1000MS 40
#define DELAI_2000MS 80
#define ROUES_AVANCENT 0x05
#define ROUE_GAUCHE_RECULE 0x06
#define ROUE_DROITE_RECULE 0x81

void manoeuvre1();
void manoeuvre2();
void manoeuvre3();
void manoeuvre4();
void manoeuvre5();
void manoeuvre6();
